name: Build Packages

on:
  release:
    types: [published]
  push:
    tags:
      - v*
    branches: [master, dev]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-src:
    name: Build Base Packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ARCH: ["x86_64"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Prepare
        run: |
          sudo apt install wget exiftool
          sudo npm install electron/asar -g
          echo "$UID, $GID"

      - name: Generate TAG
        id: Tag
        run: |
          tag='continuous'
          name='Continuous Build'
          if [ 'true' == ${{ startsWith(github.ref, 'refs/tags/') }} ];then
            tag='${{ github.ref_name }}'
            name='${{ github.ref_name }}'
          fi
          echo "tag result: $tag - $name"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          ls -l
          tools/setup-bilibili

      - name: Compress Resources
        run: |
          ls -l
          BUILD_VERSION="${{ steps.tag.outputs.tag }}"
          if [[ "$BUILD_VERSION" == *continuous ]]; then
              echo "continuous"
              sed -i 's#"buildVersion": "[0-9]\+",#"buildVersion": "0",#' "package.json"
          else
              tag=(${BUILD_VERSION//-/ })
              echo "${tag[1]}"
              sed -i 's#"buildVersion": "[0-9]\+",#"buildVersion": "'${tag[1]}'",#' "package.json"
          fi
          mkdir -p tmp/src
          mkdir -p tmp/build
          tar -zcf tmp/src/bilibili-${{ steps.tag.outputs.tag }}-${{ matrix.ARCH }}.tar.gz bin app electron
          tar -zcf tmp/build/extensions-${{ steps.tag.outputs.tag }}.tar.gz extensions

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-${{ matrix.ARCH }}.src
          path: tmp/src
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-${{ matrix.ARCH }}.build
          path: tmp/build

  build-linux:
    name: Build Linux
    needs:
      - build-src
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ARCH: ["x86_64"]

    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare
        run: |
          sudo npm install electron/asar -g
          npm ci
          echo "$UID, $GID"

      - name: Generate TAG
        id: Tag
        run: |
          tag='continuous'
          name='Continuous Build'
          if [ 'true' == ${{ startsWith(github.ref, 'refs/tags/') }} ];then
            tag='${{ github.ref_name }}'
            name='${{ github.ref_name }}'
          fi
          echo "tag result: $tag - $name"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Build
        env:
          BUILD_VERSION: ${{ steps.tag.outputs.tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -l
          mkdir -p tmp/build
          tools/build-prepare.sh
          asar e app/app.asar app/app
          npm run pkg-linux
          rm -rf tmp/build/linux-unpacked

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-linux-${{ matrix.ARCH }}.build
          path: tmp/build
  build-mac:
    name: Build Mac
    needs:
      - build-src
    runs-on: macos-latest

    strategy:
      matrix:
        ARCH: ["x86_64"]

    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare
        run: |
          npm install electron/asar -g
          npm ci

      - name: Generate TAG
        id: Tag
        run: |
          tag='continuous'
          name='Continuous Build'
          if [ 'true' == ${{ startsWith(github.ref, 'refs/tags/') }} ];then
            tag='${{ github.ref_name }}'
            name='${{ github.ref_name }}'
          fi
          echo "tag result: $tag - $name"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Build
        env:
          BUILD_VERSION: ${{ steps.tag.outputs.tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p tmp/build
          tools/build-prepare.sh
          asar e app/app.asar app/app
          npm run pkg-mac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-macos-${{ matrix.ARCH }}.build
          path: tmp/build/**.dmg

  build-win:
    name: Build Windows
    needs:
      - build-src
    runs-on: windows-latest

    strategy:
      matrix:
        ARCH: ["x86_64"]

    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare
        run: |
          npm install electron/asar -g
          npm ci

      - name: Generate TAG
        id: Tag
        run: |
          $tag='continuous'
          $name='Continuous Build'
          $ref='${{ github.ref }}'
          if ($ref.StartsWith("refs/tags/")) {
            $tag='${{ github.ref_name }}'
            $name='${{ github.ref_name }}'
          }
          Write-Output "tag result: $tag - $name"
          Write-Output "tag=$tag" >> $GITHUB_OUTPUT
          Write-Output "name=$name" >> $GITHUB_OUTPUT

      - name: Build
        env:
          BUILD_VERSION: ${{ steps.tag.outputs.tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p tmp\build
          tar -zxf $(Get-Item bilibili-*.src/bilibili-*.tar.gz | Resolve-Path -Relative)  -C .
          asar e app\app.asar app\app
          npm run pkg-win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-windows-${{ matrix.ARCH }}.build
          path: "tmp/build/bilibili Setup**.exe"

  build-deepin:
    name: Build Deepin Package
    needs:
      - build-src
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ARCH: ["x86_64", "ARM64"]

    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot devscripts debhelper # debmake lintian pbuilder

      - name: Generate TAG
        id: Tag
        run: |
          tag='continuous'
          name='Continuous Build'
          if [ 'true' == ${{ startsWith(github.ref, 'refs/tags/') }} ];then
            tag='${{ github.ref_name }}'
            name='${{ github.ref_name }}'
          else
            BILIBILI_VERSION=$(cat conf/bilibili_version)
            tag="v${BILIBILI_VERSION}-${tag}"
          fi
          echo "tag result: $tag - $name"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Build Deb Package
        run: |
          export BUILD_VERSION=${{ steps.tag.outputs.tag }}
          ls -l
          mkdir -p tmp/build
          tools/build-prepare.sh
          echo "${{ matrix.ARCH }}"
          if [ "${{ matrix.ARCH }}" == "ARM64" ];then
            export BUILD_ARCH="arm64"
            export LD_LIBRARY_PATH="/usr/aarch64-linux-gnu/lib"
            tools/update-electron
          else
            export BUILD_ARCH="amd64"
          fi
          tools/build-deepin.sh ${{ steps.tag.outputs.tag }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bilibili-deepin-${{ matrix.ARCH }}.build
          path: tmp/build

  upload:
    name: Create release and upload artifacts
    needs:
      - build-src
      - build-linux
      - build-win
      - build-deepin
      - build-mac
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Inspect directory after downloading artifacts
        run: ls -alFR

      - name: Generate TAG
        id: Tag
        run: |
          tag='continuous'
          name='Continuous Build'
          if [ 'true' == ${{ startsWith(github.ref, 'refs/tags/') }} ];then
            tag='${{ github.ref_name }}'
            name='${{ github.ref_name }}'
          fi
          echo "tag result: $tag - $name"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Create release and upload artifacts
        if: startsWith(github.ref, 'refs/heads/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt install -y fuse
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ls -l **build/*
          ./pyuploadtool-x86_64.AppImage \
          **src/*.tar.gz \
          **build/*.tar.gz \
          **build/*.AppImage \
          **build/*.deb \
          **build/*.exe \
          **build/*.dmg

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.tag.outputs.name }}
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            **src/*.tar.gz
            **build/*.tar.gz
            **build/*.AppImage
            **build/*.deb
            **build/*.exe
            **build/*.dmg
